# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal

class MyComboBox(QtWidgets.QComboBox):
    mysignal = pyqtSignal()
    def mousePressEvent(self, event):
        self.mysignal.emit()
        QtWidgets.QComboBox.mousePressEvent(self, event)
        
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser_receive = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_receive.setGeometry(QtCore.QRect(250, 141, 511, 141))
        self.textBrowser_receive.setObjectName("textBrowser_receive")
        self.textEdit_transmit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_transmit.setGeometry(QtCore.QRect(250, 350, 511, 131))
        self.textEdit_transmit.setObjectName("textEdit_transmit")
        self.lcdNumber_rx = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_rx.setGeometry(QtCore.QRect(250, 100, 91, 31))
        self.lcdNumber_rx.setDigitCount(6)
        self.lcdNumber_rx.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_rx.setObjectName("lcdNumber_rx")
        self.lcdNumber_tx = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_tx.setGeometry(QtCore.QRect(250, 310, 91, 31))
        self.lcdNumber_tx.setFrameShape(QtWidgets.QFrame.Box)
        self.lcdNumber_tx.setDigitCount(6)
        self.lcdNumber_tx.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_tx.setObjectName("lcdNumber_tx")
        self.textBrowser_status = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_status.setGeometry(QtCore.QRect(250, 40, 511, 31))
        self.textBrowser_status.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser_status.setLineWidth(0)
        self.textBrowser_status.setObjectName("textBrowser_status")
        self.pushButton_send = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_send.setGeometry(QtCore.QRect(250, 500, 111, 28))
        self.pushButton_send.setObjectName("pushButton_send")
        self.pushButton_cmd1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cmd1.setGeometry(QtCore.QRect(380, 500, 111, 28))
        self.pushButton_cmd1.setObjectName("pushButton_cmd1")
        self.pushButton_cmd2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cmd2.setGeometry(QtCore.QRect(510, 500, 111, 28))
        self.pushButton_cmd2.setObjectName("pushButton_cmd2")
        self.pushButton_cmd3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_cmd3.setGeometry(QtCore.QRect(640, 500, 111, 28))
        self.pushButton_cmd3.setObjectName("pushButton_cmd3")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(250, 20, 72, 15))
        self.label_9.setObjectName("label_9")
        self.pushButton_reset_rx = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_reset_rx.setGeometry(QtCore.QRect(670, 100, 91, 28))
        self.pushButton_reset_rx.setObjectName("pushButton_reset_rx")
        self.pushButton_reset_tx = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_reset_tx.setGeometry(QtCore.QRect(670, 310, 91, 28))
        self.pushButton_reset_tx.setObjectName("pushButton_reset_tx")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(230, 80, 551, 20))
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(230, 290, 551, 20))
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(220, 10, 20, 531))
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.checkBox_rtscts = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_rtscts.setGeometry(QtCore.QRect(50, 420, 151, 19))
        self.checkBox_rtscts.setObjectName("checkBox_rtscts")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 320, 91, 16))
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 20, 72, 15))
        self.label.setObjectName("label")
        self.comboBox_stopbits = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_stopbits.setGeometry(QtCore.QRect(50, 280, 151, 22))
        self.comboBox_stopbits.setObjectName("comboBox_stopbits")
        self.comboBox_baudrate = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_baudrate.setGeometry(QtCore.QRect(50, 100, 151, 22))
        self.comboBox_baudrate.setObjectName("comboBox_baudrate")
        self.checkBox_dsrdtr = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_dsrdtr.setGeometry(QtCore.QRect(50, 460, 141, 19))
        self.checkBox_dsrdtr.setObjectName("checkBox_dsrdtr")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 80, 72, 15))
        self.label_2.setObjectName("label_2")
        self.checkBox_xonxoff = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_xonxoff.setGeometry(QtCore.QRect(50, 380, 151, 19))
        self.checkBox_xonxoff.setObjectName("checkBox_xonxoff")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 260, 72, 15))
        self.label_5.setObjectName("label_5")
        self.pushButton_openport = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_openport.setGeometry(QtCore.QRect(30, 500, 91, 28))
        self.pushButton_openport.setObjectName("pushButton_openport")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 200, 72, 15))
        self.label_4.setObjectName("label_4")
        self.comboBox_port = MyComboBox(self.centralwidget)
        self.comboBox_port.setGeometry(QtCore.QRect(50, 40, 151, 22))
        self.comboBox_port.setObjectName("comboBox_port")
        self.comboBox_bytesize = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_bytesize.setGeometry(QtCore.QRect(50, 160, 151, 22))
        self.comboBox_bytesize.setObjectName("comboBox_bytesize")
        self.comboBox_parity = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_parity.setGeometry(QtCore.QRect(50, 220, 151, 22))
        self.comboBox_parity.setObjectName("comboBox_parity")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 140, 72, 15))
        self.label_3.setObjectName("label_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(770, 10, 20, 531))
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(220, 530, 561, 20))
        self.line_5.setLineWidth(2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(220, 0, 561, 20))
        self.line_6.setLineWidth(2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(10, 10, 20, 531))
        self.line_7.setLineWidth(2)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(20, 0, 201, 20))
        self.line_8.setLineWidth(2)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(20, 530, 201, 20))
        self.line_9.setLineWidth(2)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.lineEdit_timeout = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_timeout.setGeometry(QtCore.QRect(50, 340, 151, 21))
        self.lineEdit_timeout.setClearButtonEnabled(False)
        self.lineEdit_timeout.setObjectName("lineEdit_timeout")
        self.pushButton_closeport = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_closeport.setGeometry(QtCore.QRect(130, 500, 91, 28))
        self.pushButton_closeport.setObjectName("pushButton_closeport")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(370, 100, 151, 41))
        self.widget.setObjectName("widget")
        self.radioButton_enable_receive = QtWidgets.QRadioButton(self.widget)
        self.radioButton_enable_receive.setGeometry(QtCore.QRect(0, 0, 151, 19))
        self.radioButton_enable_receive.setObjectName("radioButton_enable_receive")
        self.radioButton_disable_receive = QtWidgets.QRadioButton(self.widget)
        self.radioButton_disable_receive.setGeometry(QtCore.QRect(0, 20, 151, 19))
        self.radioButton_disable_receive.setObjectName("radioButton_disable_receive")
        self.line.raise_()
        self.radioButton_enable_receive.raise_()
        self.radioButton_disable_receive.raise_()
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(370, 310, 120, 41))
        self.widget_2.setObjectName("widget_2")
        self.radioButton_auto_send = QtWidgets.QRadioButton(self.widget_2)
        self.radioButton_auto_send.setGeometry(QtCore.QRect(0, 0, 151, 19))
        self.radioButton_auto_send.setObjectName("radioButton_auto_send")
        self.radioButton_manual_send = QtWidgets.QRadioButton(self.widget_2)
        self.radioButton_manual_send.setGeometry(QtCore.QRect(0, 20, 151, 19))
        self.radioButton_manual_send.setObjectName("radioButton_manual_send")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(530, 100, 131, 41))
        self.widget_3.setObjectName("widget_3")
        self.radioButton_hex_display = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton_hex_display.setGeometry(QtCore.QRect(0, 0, 111, 19))
        self.radioButton_hex_display.setObjectName("radioButton_hex_display")
        self.radioButton_ascii_display = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton_ascii_display.setGeometry(QtCore.QRect(0, 20, 131, 19))
        self.radioButton_ascii_display.setObjectName("radioButton_ascii_display")
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setGeometry(QtCore.QRect(530, 310, 120, 41))
        self.widget_4.setObjectName("widget_4")
        self.radioButton_hex_send = QtWidgets.QRadioButton(self.widget_4)
        self.radioButton_hex_send.setGeometry(QtCore.QRect(0, 0, 131, 19))
        self.radioButton_hex_send.setObjectName("radioButton_hex_send")
        self.radioButton_ascii_send = QtWidgets.QRadioButton(self.widget_4)
        self.radioButton_ascii_send.setGeometry(QtCore.QRect(0, 20, 131, 19))
        self.radioButton_ascii_send.setObjectName("radioButton_ascii_send")
        self.radioButton_hex_send.raise_()
        self.radioButton_ascii_send.raise_()
        self.textEdit_transmit.raise_()
        self.textEdit_transmit.raise_()
        self.textBrowser_receive.raise_()
        self.lcdNumber_rx.raise_()
        self.lcdNumber_tx.raise_()
        self.textBrowser_status.raise_()
        self.pushButton_send.raise_()
        self.pushButton_cmd1.raise_()
        self.pushButton_cmd2.raise_()
        self.pushButton_cmd3.raise_()
        self.label_9.raise_()
        self.pushButton_reset_rx.raise_()
        self.pushButton_reset_tx.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.checkBox_rtscts.raise_()
        self.label_6.raise_()
        self.label.raise_()
        self.comboBox_stopbits.raise_()
        self.comboBox_baudrate.raise_()
        self.checkBox_dsrdtr.raise_()
        self.label_2.raise_()
        self.checkBox_xonxoff.raise_()
        self.label_5.raise_()
        self.pushButton_openport.raise_()
        self.label_4.raise_()
        self.comboBox_port.raise_()
        self.comboBox_bytesize.raise_()
        self.comboBox_parity.raise_()
        self.label_3.raise_()
        self.line_4.raise_()
        self.line_5.raise_()
        self.line_6.raise_()
        self.line_7.raise_()
        self.line_8.raise_()
        self.line_9.raise_()
        self.lineEdit_timeout.raise_()
        self.pushButton_closeport.raise_()
        self.widget.raise_()
        self.widget_2.raise_()
        self.widget_3.raise_()
        self.widget_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_send.setText(_translate("MainWindow", "Send"))
        self.pushButton_cmd1.setText(_translate("MainWindow", "CMD1"))
        self.pushButton_cmd2.setText(_translate("MainWindow", "CMD2"))
        self.pushButton_cmd3.setText(_translate("MainWindow", "CMD3"))
        self.label_9.setText(_translate("MainWindow", "Status"))
        self.pushButton_reset_rx.setText(_translate("MainWindow", "Reset"))
        self.pushButton_reset_tx.setText(_translate("MainWindow", "Reset"))
        self.checkBox_rtscts.setText(_translate("MainWindow", "rtscts enable "))
        self.label_6.setText(_translate("MainWindow", "Read Timeout"))
        self.label.setText(_translate("MainWindow", "Port"))
        self.checkBox_dsrdtr.setText(_translate("MainWindow", "dsrdtr enable "))
        self.label_2.setText(_translate("MainWindow", "BaudRate"))
        self.checkBox_xonxoff.setText(_translate("MainWindow", "xonxoff enable"))
        self.label_5.setText(_translate("MainWindow", "StopBits"))
        self.pushButton_openport.setText(_translate("MainWindow", "Open Port"))
        self.label_4.setText(_translate("MainWindow", "Parity"))
        self.label_3.setText(_translate("MainWindow", "ByteSize"))
        self.pushButton_closeport.setText(_translate("MainWindow", "Close Port"))
        self.radioButton_enable_receive.setText(_translate("MainWindow", "enable receive"))
        self.radioButton_disable_receive.setText(_translate("MainWindow", "disable receive"))
        self.radioButton_auto_send.setText(_translate("MainWindow", "auto send"))
        self.radioButton_manual_send.setText(_translate("MainWindow", "manual send"))
        self.radioButton_hex_display.setText(_translate("MainWindow", "hex display"))
        self.radioButton_ascii_display.setText(_translate("MainWindow", "ascii dispaly"))
        self.radioButton_hex_send.setText(_translate("MainWindow", "hex send"))
        self.radioButton_ascii_send.setText(_translate("MainWindow", "ascii send"))

