clear all

theta=0:0.01:2*pi;
Vs = sqrt(4)/2;
Vdc = 1;
y = sqrt(3)/4 - (sqrt(3)/2)*sqrt(Vs*Vs - 3/4);
x = 1 - y / sqrt(3);
alpha = atan(y/x);
%constant

temp1 = (1/2)*Vs*Vdc;
temp2 = (1/2)*Vdc;
temp3 = sqrt(3);
temp4 = 1/sqrt(3);

y=((temp1)*cos(theta)+(temp1*temp4)*sin(theta)).*(theta>=0 & theta<(alpha)) ...
    +(temp2).*(theta>=(alpha) & theta<(pi/3 - alpha)) ...
    +((temp1)*cos(theta)+(temp1*temp4)*sin(theta)).*(theta>=(pi/3 - alpha) & theta<(pi/3)) ...%sector 1
    +((temp1)*cos(theta-pi/3)+(-temp1*temp3)*sin(theta-pi/3)).*(theta>=(pi/3) & theta<(pi/3 + alpha)) ...
    +((temp2)*((cos(theta-pi/3) - temp3*sin(theta-pi/3))./(cos(theta-pi/3) + temp4*sin(theta-pi/3)))).*(theta>=(pi/3 + alpha) & theta<(2*pi/3 - alpha)) ...
    +((temp1)*cos(theta-pi/3)+(-temp1*temp3)*sin(theta-pi/3)).*(theta>=(2*pi/3 - alpha) & theta<(2*pi/3)) ...%sector 2
    +((-temp1)*cos(theta-2*pi/3)+(-temp1*temp4)*sin(theta-2*pi/3)).*(theta>=(2*pi/3) & theta<(2*pi/3 + alpha)) ...
    +(-temp2).*(theta>=(2*pi/3 + alpha) & theta<(pi - alpha)) ...
    +((-temp1)*cos(theta-2*pi/3)+(-temp1*temp4)*sin(theta-2*pi/3)).*(theta>=(pi - alpha) & theta<(pi)) ...%sector3
    +((-temp1)*cos(theta-pi)+(-temp1*temp4)*sin(theta-pi)).*(theta>=(pi) & theta<(pi + alpha)) ...
    +(-temp2).*(theta>=(pi + alpha) & theta<(4*pi/3 - alpha)) ...
    +((-temp1)*cos(theta-pi)+(-temp1*temp4)*sin(theta-pi)).*(theta>=(4*pi/3 - alpha) & theta<(4*pi/3)) ...%sector4
    +((-temp1)*cos(theta-4*pi/3)+(temp1*temp3)*sin(theta-4*pi/3)).*(theta>=(4*pi/3) & theta<(4*pi/3 + alpha)) ...
    +((temp2)*((-cos(theta-4*pi/3) + temp3*sin(theta-4*pi/3))./(cos(theta-4*pi/3) + temp4*sin(theta-4*pi/3)))).*(theta>=(4*pi/3 + alpha) & theta<(5*pi/3 - alpha)) ...
    +((-temp1)*cos(theta-4*pi/3)+(temp1*temp3)*sin(theta-4*pi/3)).*(theta>=(5*pi/3 - alpha) & theta<(5*pi/3)) ...%sector 5
    +((temp1)*cos(theta-5*pi/3)+(temp1*temp4)*sin(theta-5*pi/3)).*(theta>=5*pi/3 & theta<(5*pi/3 + alpha)) ...
    +(temp2).*(theta>=(5*pi/3 + alpha) & theta<(2*pi - alpha)) ...
    +((temp1)*cos(theta-5*pi/3)+(temp1*temp4)*sin(theta-5*pi/3)).*(theta>=(2*pi - alpha) & theta<=(2*pi));%sector 6

plot(theta,y,'r')

grid on