clear all
temp1 = sqrt(3)/2;
temp2 = 1/2;
temp3 = 3/2;
y = @(theta) ( ...   
         ((temp1)*cos(theta)+(temp2)*sin(theta)).*cos(theta).*(theta>=0 & theta<(pi/3)) ...
        +((temp1)*cos(theta-pi/3)+(-temp3)*sin(theta-pi/3)).*cos(theta).*(theta>=(pi/3) & theta<(2*pi/3)) ...
        +((-temp1)*cos(theta-2*pi/3)+(-temp2)*sin(theta-2*pi/3)).*cos(theta).*(theta>=(2*pi/3) & theta<(pi)) ...
        +((-temp1)*cos(theta-pi)+(-temp2)*sin(theta-pi)).*cos(theta).*(theta>=(pi) & theta<(4*pi/3)) ...
        +((-temp1)*cos(theta-4*pi/3)+(temp3)*sin(theta-4*pi/3)).*cos(theta).*(theta>=(4*pi/3) & theta<(5*pi/3)) ...
        +((temp1)*cos(theta-5*pi/3)+(temp2)*sin(theta-5*pi/3)).*cos(theta).*(theta>=(5*pi/3) & theta<=(2*pi)) ...
        );
F=integral(y,0,2*pi)/(2*pi);